apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::307417376574:user/iamhenryeffiong
      username: iamhenryeffiong
      groups:
        - system:masters
